In [14]:
import numpy as np
import pandas as pd

In [15]:
a = [2, 5, 7]

In [16]:
b = [3, 12, 27]

In [17]:
a+b

[2, 5, 7, 3, 12, 27]

In [18]:
c = [m+n for m, n in zip(a,b)]

In [19]:
c

[5, 17, 34]

In [20]:
sum(a)

14

In [21]:
np_a = np.array(a)

In [22]:
np_b = np.array(b)

In [23]:
np_a + np_b

array([ 5, 17, 34])

In [24]:
p = np.array([1,2,"abc"])

In [25]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [26]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [27]:
np_a.max()

7

In [28]:
np_a.mean()

4.666666666666667

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np_a*np.ones(3)

array([2., 5., 7.])

In [32]:
np_a*[3]

array([ 6, 15, 21])

In [33]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [34]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [35]:
np_a[1]

5

In [36]:
np_a[1:]

array([5, 7])

In [37]:
np_a[0:2]

array([2, 5])

In [38]:
np_2d = np.array([[1,2],[3,4]])

In [39]:
np_2d.sum()

10

In [40]:
np_2d.sum(axis=0)

array([4, 6])

In [41]:
np_2d.sum(axis=1)

array([3, 7])

In [42]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [43]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [44]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [45]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
np_2d

array([[1, 2],
       [3, 4]])

In [47]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [48]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [49]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [50]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [51]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [52]:
np_dotp[0,1]

210

In [53]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [54]:
np_dotp[0:2,0]

array([2001, 4003])

In [55]:
np_rs = np.array([1,2,3,4,5,6])

In [56]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [57]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [61]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [63]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.random(2)

TypeError: 'module' object is not callable

In [65]:
np.random.random(2)

array([0.70693952, 0.73985788])

In [66]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [67]:
import numpy.random as random

In [68]:
random(2)

TypeError: 'module' object is not callable

In [69]:
random.random(2)

array([0.92865078, 0.94033944])

In [70]:
random.random([3,2])

array([[0.944174  , 0.79019816],
       [0.52048267, 0.44167043],
       [0.522961  , 0.55982451]])

In [73]:
import numpy.linalg as la

In [74]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
la.eig(np_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [76]:
la.svd(np_2d)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [77]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [78]:
random.rand(2,3)*5

array([[1.30443832, 1.16924114, 4.04049107],
       [3.10674531, 2.10202413, 1.52159786]])

In [79]:
random.randn(2,3)

array([[-0.59574839, -1.79020285, -0.02207161],
       [-1.32137769, -0.66151701,  1.07596351]])

In [80]:
random.randint(-2,3,5)

array([-1,  1, -2,  0, -2])

In [81]:
random.shuffle(np_rs)

In [82]:
np_rs

array([4, 5, 2, 6, 3, 1])

In [83]:
random.choice(np_rs, 2)

array([1, 1])

In [84]:
random.binomial(20,0.3)

3

In [85]:
random.binomial(20, 0.3, 7)

array([6, 4, 9, 8, 8, 6, 7])

In [86]:
random.exponential(0.7,4)

array([1.67504933, 0.09109557, 0.02890336, 0.5867762 ])

In [87]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [88]:
random.normal(-5,12,3)

array([ 4.91051465, 18.25118017,  6.4732861 ])

In [89]:
random.logistic(-2,4,7)

array([-9.07094108, -4.36744232,  4.29327979, -8.98657277, -0.0483736 ,
       11.60001504, -1.84421407])

In [90]:
np_2d.shape

(2, 2)

In [91]:
np_2d.dtype

dtype('int32')

In [92]:
type(np_2d)

numpy.ndarray

In [93]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [94]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [95]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [96]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [97]:
np_x = np.array(x)
np_y = np.array(y)

In [98]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: total: 1.11 s
Wall time: 1.2 s


In [99]:
%%time
np_z = np_x+np_y

CPU times: total: 15.6 ms
Wall time: 13.9 ms


In [101]:
data = pd.read_csv('NumpyExerciseData.csv')
data

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0    1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1    1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2    1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3    1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4    1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   
5    1  1.063  42.14   0   6 -2.1   8         NaN         NaN         NaN   
6    1  5.306  39.80   0  29 -1.8  30         NaN         NaN         NaN   
7    1  4.309  36.14   0  12 -3.4  22         NaN         NaN         NaN   
8    1  3.739  44.53   0  39  1.9  24         NaN         NaN         NaN   
9    1  3.816  60.01   0  10 -3.4  24         NaN         NaN         NaN   
10   1  8.539  36.90   0  31 -3.0  43         NaN         NaN         NaN   
11   1  7.129  35.77   0  38  3.5  30         NaN         NaN         NaN   
12   1  4.249  37.17   0  23  0.8  20         NaN         NaN         NaN   
13   1 -2.990  42.41   0  20 -3.1   2         NaN         NaN         NaN   
14   1  0.356  57.67   0  26 -3.8  19         NaN         NaN         NaN   
15   1  5.487  35.25   0  10 -2.8  24         NaN         NaN         NaN   
16   1  5.699  62.15   0  13  2.4  22         NaN         NaN         NaN   
17   1 -0.373  38.38   1  42  2.0  23         NaN         NaN         NaN   
18   1  3.900  40.53   0  23 -2.5  25         NaN         NaN         NaN   
19   1  3.616  35.91   1  16  3.1  23         NaN         NaN         NaN   
20   1  9.103  59.60   0  14  2.2  34         NaN         NaN         NaN   
21   1  2.714  43.54   0  37  2.1  19         NaN         NaN         NaN   
22   1  6.885  35.66   1  20 -3.7  46         NaN         NaN         NaN   
23   1 -0.850  43.94   1  31 -3.2  26         NaN         NaN         NaN   
24   1  5.511  58.96   0   6 -3.8  28         NaN         NaN         NaN   
25   1  5.225  45.25   0  24 -1.3  28         NaN         NaN         NaN   
26   1  7.982  43.71   0  27  2.0  33         NaN         NaN         NaN   
27   1  4.361  52.71   0  22 -2.5  28         NaN         NaN         NaN   
28   1  2.853  51.12   0  42  2.3  22         NaN         NaN         NaN   
29   1  2.777  38.60   1  24 -2.5  33         NaN         NaN         NaN   
30   1  1.977  49.07   0  41 -3.6  28         NaN         NaN         NaN   
31   1  3.784  45.44   0  12 -1.9  20         NaN         NaN         NaN   
32   1  3.043  62.50   0  25 -1.9  25         NaN         NaN         NaN   
33   1  5.618  52.44   0  27  1.1  28         NaN         NaN         NaN   
34   1  7.374  38.25   0  36  3.1  31         NaN         NaN         NaN   
35   1  3.090  56.77   0  49 -1.7  33         NaN         NaN         NaN   
36   1  6.178  61.51   1   6 -2.5  41         NaN         NaN         NaN   
37   1  4.605  58.22   0  41  0.2  32         NaN         NaN         NaN   
38   1  1.968  65.84   0  76  3.5  33         NaN         NaN         NaN   
39   1  3.610  45.18   1  43  2.5  36         NaN         NaN         NaN   
40   1  9.896  65.18   0  69  2.3  58         NaN         NaN         NaN   
41   1 -0.256  53.70   0  13  0.3   5         NaN         NaN         NaN   
42   1  4.545  39.25   1  18  2.2  29         NaN         NaN         NaN   
43   1  3.121  36.89   0  20  4.1  10         NaN         NaN         NaN   
44   1  4.698  40.65   0   8 -1.8  20         NaN         NaN         NaN   
45   1 -0.328  49.64   0  18  0.5   6         NaN         NaN         NaN   
46   1  5.216  44.49   1  11  3.2  28         NaN         NaN         NaN   
47   1 -2.111  51.31   0  25  2.6  -1         NaN         NaN         NaN   
48   1  6.804  36.12   0  24  3.0  25         NaN         NaN         NaN   
49   1  5.643  39.06   0  35 -1.9  34         NaN         NaN         NaN   

    Unnamed: 10  
0           NaN  
1           NaN  
2           NaN  
3   

In [102]:
data.shape

(50, 11)

In [103]:
np_Arr = data.to_numpy()

In [104]:
np_Arr.shape

(50, 11)

Newton Method
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41

In [105]:
#Train-test Split
train_Arr = np_Arr[:42,0:6] #X Values
train_Y = np_Arr[:42,6:7] #y column
print("Shape 'X' Values (Train) : ",train_Arr.shape)
print("Shape 'y' Value (Train) : ",train_Y.shape)

test_Arr = np_Arr[43:,0:6] 
test_Y = np_Arr[43:,6:7]
print("Shape 'X' Values (Test) : ",train_Arr.shape)
print("Shape 'y' Value (Test) : ",train_Y.shape)


Shape 'X' Values (Train) :  (42, 6)
Shape 'y' Value (Train) :  (42, 1)
Shape 'X' Values (Test) :  (42, 6)
Shape 'y' Value (Test) :  (42, 1)


In [106]:
# X'
train_Trans = train_Arr.transpose()
train_Trans.shape

(6, 42)

In [107]:
test_Trans = test_Arr.transpose()
test_Trans.shape

(6, 7)

In [108]:
#Inverse
train_Inv = la.inv(np.dot(train_Trans,train_Arr))
train_Inv.shape

(6, 6)

Weight - Newton's Method

In [109]:
# ((X'X)^-1)*X'y
w = np.dot(train_Inv,np.dot(train_Trans,train_Y))
w

array([[-7.81255606],
       [ 3.26009384],
       [ 0.16690469],
       [12.18239059],
       [ 0.38161309],
       [-1.5843724 ]])

In [110]:
print(train_Trans.shape)
print(train_Inv)
print(train_Y.shape)

(6, 42)
[[ 6.98784524e-01 -1.36572910e-02 -1.08940206e-02 -1.17233989e-01
  -2.48840513e-03  1.40406328e-02]
 [-1.36572910e-02  3.32700514e-03 -8.64950521e-05  3.92057018e-03
   8.75994966e-05 -1.26040786e-03]
 [-1.08940206e-02 -8.64950521e-05  2.49512745e-04  1.44798576e-03
  -3.47021598e-05  7.48545978e-05]
 [-1.17233989e-01  3.92057018e-03  1.44798576e-03  1.86040503e-01
  -1.57825891e-05 -5.53822334e-04]
 [-2.48840513e-03  8.75994966e-05 -3.47021598e-05 -1.57825891e-05
   1.34016398e-04 -3.73740932e-04]
 [ 1.40406328e-02 -1.26040786e-03  7.48545978e-05 -5.53822334e-04
  -3.73740932e-04  4.94203097e-03]]
(42, 1)


Y Value Prediction - Newton's Method

In [111]:
y_Train_Pred = np.dot(train_Arr,w)
y_Test_Pred = np.dot(test_Arr,w)
print(y_Train_Pred)
print(y_Test_Pred)

[[27.99735178]
 [46.0019147 ]
 [14.28976738]
 [17.04177241]
 [31.67075174]
 [ 8.30314785]
 [30.04695842]
 [22.233347  ]
 [23.68180355]
 [23.84690947]
 [42.76729129]
 [30.35482768]
 [19.75303311]
 [ 2.06200743]
 [18.9159862 ]
 [24.21134276]
 [22.29832155]
 [22.41862645]
 [24.40448903]
 [23.34613623]
 [33.66856162]
 [19.09487106]
 [46.26184153]
 [25.83254426]
 [28.30481522]
 [27.99226972]
 [32.63972557]
 [27.55867831]
 [22.40435261]
 [32.98528128]
 [28.17253988]
 [19.69745273]
 [25.09008735]
 [27.81587681]
 [31.43799708]
 [33.12878759]
 [41.02761124]
 [32.24662927]
 [33.04960476]
 [36.12795901]
 [58.01542692]
 [ 4.80130013]]
[[ 9.65564574]
 [20.19281545]
 [ 5.48013131]
 [27.92782592]
 [-0.7097756 ]
 [24.80331676]
 [33.47021636]]


Error Computation (both Training and Test Error)
Generate y values from the new generated w values
Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51

In [112]:
newt_ssr_train = np.sum(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_ssr_test = np.sum(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("SSR - Newton's Method (Train) : ",newt_ssr_train)
print("SSR - Newton's Method (Test) : ",newt_ssr_test)

SSR - Newton's Method (Train) :  2.9540159678699496
SSR - Newton's Method (Test) :  0.834815415560693


In [113]:
# MSR and RMSE
newt_msr_train = np.mean(np.power(np.subtract(train_Y,y_Train_Pred),2))
newt_msr_test = np.mean(np.power(np.subtract(test_Y,y_Test_Pred),2))
print("MSR - Newton's Method (Train) : ",newt_msr_train)
print("MSR - Newton's Method (Test) : ",newt_msr_test)

MSR - Newton's Method (Train) :  0.07033371352071309
MSR - Newton's Method (Test) :  0.11925934508009901


In [114]:
newt_rmse_train = np.sqrt(newt_msr_train)
newt_rmse_test = np.sqrt(newt_msr_test)
print("RMSE - Newton's Method (Train) : ",newt_rmse_train)
print("RMSE - Newton's Method (Test) : ",newt_rmse_test)

RMSE - Newton's Method (Train) :  0.2652050405265954
RMSE - Newton's Method (Test) :  0.3453394635429015


Regularized Newton
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41
Use lambda as 0.17
Compute and report both training and test errors for the regularized newton computation

In [115]:
# ((X'X+lambda*I)^-1)*X'y
reg_Newt_Train_W = np.dot(la.inv(np.add(np.dot(train_Trans,train_Arr),np.dot(0.17,np.identity(train_Arr.shape[1])))),np.dot(train_Trans,train_Y))
print("Regularized Newton's Method - Weights : ",reg_Newt_Train_W)

Regularized Newton's Method - Weights :  [[-6.76458303]
 [ 3.23443812]
 [ 0.15156595]
 [11.6759603 ]
 [ 0.37862746]
 [-1.5650966 ]]


In [116]:
y_Reg_Newt_Train_Pred = np.dot(train_Arr,reg_Newt_Train_W)
y_Reg_Newt_Test_Pred = np.dot(test_Arr,reg_Newt_Train_W)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Train_Pred)
print("Y - Prediction - Regularized Newton's Method : ",y_Reg_Newt_Test_Pred)


Y - Prediction - Regularized Newton's Method :  [[27.90442388]
 [45.67481598]
 [14.65825923]
 [17.22958364]
 [31.93986893]
 [ 8.61908135]
 [30.22704069]
 [22.51506218]
 [23.8710003 ]
 [23.78110841]
 [42.87980875]
 [30.62524582]
 [20.0686052 ]
 [ 2.41670754]
 [18.91936626]
 [24.49402371]
 [22.25422863]
 [22.2941932 ]
 [24.61386666]
 [23.25607865]
 [33.56940962]
 [19.33537669]
 [45.94873213]
 [25.5676731 ]
 [28.21586557]
 [28.11539999]
 [32.77039794]
 [27.57238841]
 [22.51395146]
 [32.74365814]
 [28.22531596]
 [19.87890057]
 [24.99005401]
 [27.85594388]
 [31.66235042]
 [33.04763956]
 [40.40106368]
 [32.16488068]
 [32.87774233]
 [35.80368785]
 [57.64805792]
 [ 4.99912022]]
Y - Prediction - Regularized Newton's Method :  [[10.07701936]
 [20.43815661]
 [ 5.73100093]
 [27.68196849]
 [-0.41919772]
 [25.1088653 ]
 [33.63316198]]


Compute R-squared values for both Newton and Regularized Newton on both train and test datasets
Look up how to compute R-squared values in excel

In [117]:
ssr_reg_train= np.sum(np.power(np.subtract(train_Y,y_Reg_Newt_Train_Pred),2))
ssr_reg_test = np.sum(np.power(np.subtract(test_Y,y_Reg_Newt_Test_Pred),2))
print("SSR - Regularized Newton's Method (Train) : ",ssr_reg_train)
print("SSR - Regularized Newton's Method (Test) : ",ssr_reg_test)

SSR - Regularized Newton's Method (Train) :  5.184206219816345
SSR - Regularized Newton's Method (Test) :  0.8551708105164406


In [118]:
sst_train = np.sum(np.power(train_Y-np.mean(train_Y),2))
sst_test = np.sum(np.power(test_Y-np.mean(test_Y),2))
print("SST - Regularized Newton's Method (Train) : ",sst_train)
print("SST - Regularized Newton's Method (Test) : ",sst_test)


SST - Regularized Newton's Method (Train) :  4605.071428571428
SST - Regularized Newton's Method (Test) :  975.7142857142856


In [119]:
R_squared_Newt_Train = 1 - (newt_ssr_train / sst_train) #For Newton Train Set
R_squared_Newt_Test = 1 - (newt_ssr_test / sst_test) 
print("R-Squared - Newton's Method (Train) : ",R_squared_Newt_Train)
print("R-Squared - Newton's Method (Test) : ",R_squared_Newt_Test)

R-Squared - Newton's Method (Train) :  0.9993585298265859
R-Squared - Newton's Method (Test) :  0.99914440586985


In [120]:
R_squared_Newt_Reg_Train= 1 - (ssr_reg_train / sst_train) #For Regularized Newton Train Set
R_squared_Newt_Reg_Test = 1 - (ssr_reg_test / sst_test)
print("R-Squared - Regularized Newton's Method (Train) : ",R_squared_Newt_Reg_Train)
print("R-Squared - Regularized Newton's Method (Test) : ",R_squared_Newt_Reg_Test)


R-Squared - Regularized Newton's Method (Train) :  0.9988742397810266
R-Squared - Regularized Newton's Method (Test) :  0.9991235438252394


Let's try some more things
For each of the below report the following, MSR on train, MSR on test, R-squared on train and R-squared on test
1. Use only rows 2 to 41 for training and rows 42 to 51 for testing and lambda as 0.83
2. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.17
3. Use only rows 2 to 26 for training and rows 27 to 51 for testing and lambda as 0.83
4. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.17
5. Use only rows 2 to 11 for training and rows 12 to 51 for testing and lambda as 0.83

In [121]:
train_Arr = np_Arr[:42,0:6] #X Values
train_Y = np_Arr[:42,6:7] #y column
print("Shape 'X' Values (Train) : ",train_Arr.shape)
print("Shape 'y' Value (Train) : ",train_Y.shape)

test_Arr = np_Arr[43:,0:6] 
test_Y = np_Arr[43:,6:7]
print("Shape 'X' Values (Test) : ",train_Arr.shape)
print("Shape 'y' Value (Test) : ",train_Y.shape)

Shape 'X' Values (Train) :  (42, 6)
Shape 'y' Value (Train) :  (42, 1)
Shape 'X' Values (Test) :  (42, 6)
Shape 'y' Value (Test) :  (42, 1)


In [122]:
lambda_Arr = np.array([0.83,0.17,0.83,0.17,0.83])
new_Dict = {0:[2,41,42,51],1:[2,26,27,51],2:[2,26,27,51],3:[2,11,12,51],4:[2,11,12,51]}
for i in range(len(lambda_Arr)):
    print("For lambda : ",lambda_Arr[i])
    train_Arr = np_Arr[:new_Dict[i][1]+1,0:6] #X Values
    train_Y = np_Arr[:new_Dict[i][1]+1,6:7] #y column
    test_Arr = np_Arr[new_Dict[i][2]:new_Dict[i][3]+1,0:6] 
    test_Y = np_Arr[new_Dict[i][2]:new_Dict[i][3]+1,6:7]
    train_Trans = train_Arr.transpose()
    test_Trans = test_Arr.transpose()
    print(train_Trans.shape)
    print(train_Arr.shape)
    train_Inv = la.inv(np.dot(train_Trans,train_Arr))
    w = np.dot(train_Inv,np.dot(train_Trans,train_Y))
    y_Train_Pred = np.dot(train_Arr,w)
    y_Test_Pred = np.dot(test_Arr,w)
    newt_ssr_train = np.sum(np.power(np.subtract(train_Y,y_Train_Pred),2))
    newt_ssr_test = np.sum(np.power(np.subtract(test_Y,y_Test_Pred),2))
    newt_msr_train = np.mean(np.power(np.subtract(train_Y,y_Train_Pred),2))
    newt_msr_test = np.mean(np.power(np.subtract(test_Y,y_Test_Pred),2))
    print("MSR - Newton's Method (Train) : ",newt_msr_train)
    print("MSR - Newton's Method (Test) : ",newt_msr_test)
    newt_rmse_train = np.sqrt(newt_msr_train)
    newt_rmse_test = np.sqrt(newt_msr_test)
    reg_Newt_Train_W = np.dot(np.linalg.inv(np.add(np.dot(train_Trans,train_Arr),np.dot(lambda_Arr[i],np.identity(train_Arr.shape[1])))),np.dot(train_Trans,train_Y))
    y_Reg_Newt_Train_Pred = np.dot(train_Arr,reg_Newt_Train_W)
    y_Reg_Newt_Test_Pred = np.dot(test_Arr,reg_Newt_Train_W)
    ssr_reg_train= np.sum(np.power(np.subtract(train_Y,y_Reg_Newt_Train_Pred),2))
    ssr_reg_test = np.sum(np.power(np.subtract(test_Y,y_Reg_Newt_Test_Pred),2))
    sst_train = np.sum(np.power(train_Y-np.mean(train_Y),2))
    sst_test = np.sum(np.power(test_Y-np.mean(test_Y),2))
    R_squared_Newt_Train = 1 - (newt_ssr_train / sst_train) #For Newton Train Set
    R_squared_Newt_Test = 1 - (newt_ssr_test / sst_test) 
    print("R-Squared - Newton's Method (Train) : ",R_squared_Newt_Train)
    print("R-Squared - Newton's Method (Test) : ",R_squared_Newt_Test)
    R_squared_Newt_Reg_Train= 1 - (ssr_reg_train / sst_train) #For Regularized Newton Train Set
    R_squared_Newt_Reg_Test = 1 - (ssr_reg_test / sst_test)
    print("R-Squared - Regularized Newton's Method (Train) : ",R_squared_Newt_Reg_Train)
    print("R-Squared - Regularized Newton's Method (Test) : ",R_squared_Newt_Reg_Test)

For lambda :  0.83
(6, 42)
(42, 6)
MSR - Newton's Method (Train) :  0.07033371352071309
MSR - Newton's Method (Test) :  0.10619375965188434
R-Squared - Newton's Method (Train) :  0.9993585298265859
R-Squared - Newton's Method (Test) :  0.9992226466181264
R-Squared - Regularized Newton's Method (Train) :  0.992891310755084
R-Squared - Regularized Newton's Method (Test) :  0.9936205259861491
For lambda :  0.17
(6, 27)
(27, 6)
MSR - Newton's Method (Train) :  0.059632699715716116
MSR - Newton's Method (Test) :  0.19537189790596818
R-Squared - Newton's Method (Train) :  0.9993804196155756
R-Squared - Newton's Method (Test) :  0.9987379199659023
R-Squared - Regularized Newton's Method (Train) :  0.9979202076505581
R-Squared - Regularized Newton's Method (Test) :  0.998555815419833
For lambda :  0.83
(6, 27)
(27, 6)
MSR - Newton's Method (Train) :  0.059632699715716116
MSR - Newton's Method (Test) :  0.19537189790596818
R-Squared - Newton's Method (Train) :  0.9993804196155756
R-Squared - Ne

LinAlgError: Singular matrix

Error Explanation:
A square matrix that does not have a matrix inverse.
A matrix is singular iff its determinant is 0.